### ISSUE TITLE
handle the NeO ajax call/write a function to handle distributing it's data

### ISSUE THREAD

**Issue by Cassquatch** [koganp42/Outer_Earth#4]
write code to handle the near earth object ajax call, and a function to handle displaying the data returned that we want to use

**Comment by stevie2codes** [comment]
ive got some tasty bits happening..

**Comment by Cassquatch** [comment]
I was mainly just testing out the "issue" thing, since I think that might be a clearer way to set up things, so we can see who is doing what, since you can assign them to people. But, I want to see tasty bits, are they ready for a pull request?

**Comment by stevie2codes** [comment]
almost ive got baby yoda set up .. im Working on setting up custom fonts. Found a NASA font son!

**Comment by stevie2codes** [comment]
Its some bullshit  to setup tho jeebus

**Comment by Cassquatch** [comment]
noice, cant wait to see it, I just got home from work and am exhausted, so probably won't work on anything tonight, I'd like to get some sleep, long day

**Comment by Cassquatch** [comment]
Do you have any layout done at all?

**Comment by stevie2codes** [comment]
for sure bro. Naw i finnaly got all of my weather app finished so im just now fucking around with it

**Comment by Cassquatch** [comment]
Did you do the bonus on the weather api?

**Comment by stevie2codes** [comment]
Naw just got it functional enough.  I got bigger fish to fry now, since these projects are really what matters

**Comment by Cassquatch** [comment]
Yeah I feel the same

**Comment by stevie2codes** [comment]
im just going to keep this branch open for now. All i got was the favicon tonight. The font was a fail so far. Ill be adding more to it friday

**Comment by Cassquatch** [comment]
aight then
